### ISSUE TITLE
Ungalukku enna pa, pudhu repo lam create panreenga

### ISSUE THREAD

**Issue by shrivaths16** [gitttt-1234/ECE-226-project#1]
![image](https://github.com/gitttt-1234/ECE-226-project/assets/52810689/407c7a1f-bbde-4571-8a29-bbe2c138425d)

**Comment by gitttt-1234** [comment]
oru repo create pannathu thappa :(, create panni 1 day kooda aagala athukulla issue open pandrathulam konjam over ah illa
